# Generated by Django 5.2.5 on 2025-11-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0010_alter_noticia_imagem_alter_projeto_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='area_conhecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_projetos', to='repex.areaconhecimento'),
        ),
    ]
